version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3304:3306"
    volumes:
      - devdojo_springboot_data:/var/lib/springboot2_mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
  devdojo_springboot_data: