version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3304:3306"
    volumes:
      - devdojo_springboot_data:/var/lib/springboot2_mysql

volumes:
  devdojo_springboot_data: